FROM alpine:3.12 
RUN apk --no-cache add make gcc bash musl-dev nano
COPY . /sasm-src 
WORKDIR /sasm-src 
RUN make && make install && \
    adduser -Ds /bin/bash user && \ 
    rm -rf /sasm-src
USER user 
WORKDIR /home/user
CMD [ "bash" ]
