name: Build Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install NSIS
      run: |
        irm get.scoop.sh -outfile 'install.ps1'
        .\install.ps1 -RunAsAdmin
        scoop bucket add extras
        scoop install nsis
    - name: generate installer with NSIS script
      run: |
        cd .\windows-installer\
        makensis installer.nsi