name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make run
      run: make run
    - name: cat code.asm
      run: cat code.asm
    - name: make test compiling
      run: make test
    - name: make test runnning
      run: make run_test
