name: C/C++ CI Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install compiler
      uses: rlalik/setup-cpp-compiler@v1
      with:
        compiler: latest
    
