name: C/C++ CI Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v2
    
